version: '3.9'

services:
  # mongo service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    
  # api service
  api: 
    container_name: api_container
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGO_URI : mongodb://mongo_db:27017
    depends_on:
      - mongo_db